version: '3.8'

services:
  main:
    image: venkateshsambana/vizag-resort-main:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./resort_booking.db:/app/resort_booking.db
    depends_on:
      - gateway

  admin:
    image: venkateshsambana/vizag-resort-admin:latest
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    volumes:
      - ./resort_booking.db:/app/resort_booking.db
    depends_on:
      - gateway

  booking:
    image: venkateshsambana/vizag-resort-booking:latest
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
    volumes:
      - ./resort_booking.db:/app/resort_booking.db
    depends_on:
      - gateway

  gateway:
    image: venkateshsambana/vizag-resort-gateway:latest
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./resort_booking.db:/app/resort_booking.db

networks:
  default:
    driver: bridge