FROM node:16-slim

WORKDIR /app

COPY package*.json ./
RUN npm install --production

COPY database-api.js ./
COPY db-client.js ./
COPY resort_booking.db ./

EXPOSE 3003

CMD ["node", "database-api.js"]