server {
    listen 80;
    server_name vshakago.in www.vshakago.in;
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl;
    server_name vshakago.in www.vshakago.in;
    
    ssl_certificate /etc/letsencrypt/live/vshakago.in/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/vshakago.in/privkey.pem;
    
    # Redirect /vshinteriors to /vshinteriors/
    location = /vshinteriors {
        return 301 /vshinteriors/;
    }
    
    # Interior service location
    location /vshinteriors/ {
        proxy_pass http://localhost:3006/vshinteriors/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
    }
    
    location / {
        proxy_pass http://localhost:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Disable caching
        proxy_no_cache 1;
        proxy_cache_bypass 1;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        add_header Pragma "no-cache";
        expires off;
    }
}
