name: resort_app
description: Vizag Resort Booking Mobile App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  cupertino_icons: ^1.0.2
  razorpay_flutter: ^1.3.7
  shared_preferences: ^2.2.3
  carousel_slider: ^5.0.0
  url_launcher: ^6.2.6
  google_fonts: ^6.2.1
  web_socket_channel: ^3.0.1
  youtube_player_flutter: ^9.0.3
  video_player: ^2.8.2
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/logo.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/logo.png"
  adaptive_icon_background: "#0D6EFD"
  adaptive_icon_foreground: "assets/logo.png"
